version: '3'

services:
  server:
    build: ./
    command: node server/index.cjs
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
  nginx:
    container_name: ob_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    volumes:
      - ./nginx/certs:/etc/ssl/certs
#  db:
#    image: mysql
#    restart: always
#    volumes:
#      - db:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: 'selit'
#      MYSQL_ROOT_PASSWORD: 'UjkjdjkjvrfSELIT'
#    ports:
#      - '3306:3306'

volumes:
  db:
